name: AutoBuild

on:
  push:
    branches: [ "master"]

jobs:
  build_Windows:
    runs-on: windows-latest
    env:
      Solution_Name: WonderLabX.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Build
      run: dotnet build WonderLab\WonderLabX.csproj --configuration Release
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: WonderLab\bin\Release\net6.0
  build_Linux:
    runs-on: windows-latest
    env:
      Solution_Name: WonderLabX.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Build
      run: dotnet build WonderLab\WonderLabX.csproj --configuration Release -p:RuntimeIdentifier=linux-x64
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: WonderLab\bin\Release\net6.0
  build_MacOS:
    runs-on: windows-latest
    env:
      Solution_Name: WonderLabX.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Build
      run: dotnet build WonderLab\WonderLabX.csproj --configuration Release -t:BundleApp -p:RuntimeIdentifier=osx-x64
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: WonderLab\bin\Release\net6.0
  build_Linux_Package:
    runs-on: ubuntu-latest
    env:
      Solution_Name: WonderLabX.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Build
      run: dotnet publish WonderLab\WonderLabX.csproj -c Release -r "linux-x64" \
        --self-contained true \
        -p:PublishSingleFile="false" \
        -p:PublishReadyToRun=true \
        -t:CreateDeb -t:CreateRpm
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux-package
        path: WonderLab\bin\Release\net6.0
